[agent]
name = "jetpack"

[all]
push=["./agents/jetpack/coder:/code/coder", "./agents/jetpack/chat:/code/chat"]

[[actors]]
name="frontend"
push=["./agents/jetpack/frontend:/code", "./agents/jetpack/templates:/templates"]
wit="external:frontend_wit:app"
wit_query="external:frontend_queries:app"
