[agent]
name = "coder"

[all]
push="./examples/coder/common:/code/common"

[[actors]]
name="frontend"
push="./examples/coder/frontend:/code"
wit="/code:frontend_wit:app"
wit_query="/code:frontend_queries:app"

[[actors]]
name="generator"
push="./examples/coder/generator:/code"
wit="/code:gen_wit:app"
notify="frontend"