[agent]
name = "chatbot"

[all]
push="./examples/chatbot/common:/common"

[[actors]]
name="frontend"
push="./examples/chatbot/frontend:/"
wit="/:frontend_wit:app"
wit_query="/:frontend_queries:app"

[[actors]]
name="head"
push="./examples/chatbot/head:/"
wit="/:head_wit:app"
notify="frontend"